### ISSUE TITLE
Notifications about comments.

### ISSUE THREAD

**Issue by kermitas** [sue445/chrome-gitlab-notifier#63]
Hi,

does it support notifications about comments posted under commit?
Or (what is more important for me) notification that:
- line of code was commented?
- you were mentioned in comment made under specified line of code?

**Comment by sue445** [comment]
@kermitas Sorry, this is very difficult

## because
to get new events(new MRs or issues) , use this API
https://github.com/gitlabhq/gitlabhq/blob/v7.12.2/doc/api/projects.md#get-project-events

example

```javascript
for(var project in focus_projects){
  // get project events and whether new event
}
```

This event API **not** include commit comments

If get comments, require own `sha`

https://github.com/gitlabhq/gitlabhq/blob/v7.12.2/doc/api/commits.md#get-the-comments-of-a-commit

example

```javascript
for(var project in focus_projects){
  for(var sha in all_commits) {
     // get all comments and check whether new comment
  }
}
```

I think this polling is very heavy for both client(Chrome extension) and server(Gitlab API)

This is similar to the #33

**Comment by sue445** [comment]
@kermitas  GitLab v8.3.0 supports comment event notification and this extension supports this at v1.4.0 too!
